### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by r0hitsharma** [openexchangerates/javascript-sandbox-console#12]
I couldn't find the license information for this project either in this repo or on the project page. Can you add a license or clarify? WTFPL?

**Comment by Naatan** [comment]
Bump.

**Comment by Zlatkovsky** [comment]
Bump again

**Comment by kgividen** [comment]
+1

**Comment by wjcrowcroft** [comment]
Hi all, apologies for the delay. MIT license now added – thank you to the PR from kgividen.
